#!/usr/bin/env python3
"""
Demo of the new user input system with wallet address
"""

print("🎯 DEMO: UPDATED USER INPUT SYSTEM")
print("=" * 50)
print()
print("The system now asks for:")
print("1. 🔗 Hyperliquid Wallet Address (with validation)")
print("2. 💰 Lohn-Einkommen in EUR") 
print("3. 📅 Steuerjahr")
print()
print("Example interaction:")
print("-" * 30)
print("🔗 Ihre Hyperliquid Wallet-Adresse (0x...): 0x2987F53372c02D1a4C67241aA1840C1E83c480fF")
print("💰 Ihr Lohn-Einkommen in EUR (0 wenn keines): €50000")
print("📅 Steuerjahr (2025 für aktuelles Jahr): 2025")
print()
print("✅ Wallet-Adresse: 0x2987f53372c02d1a4c67241aa1840c1e83c480ff")
print("✅ Jahreseinkommen: €50,000.00")
print("✅ Steuerjahr: 2025")
print()
print("🔒 Validation features:")
print("  • Wallet must start with 0x")
print("  • Wallet must be exactly 42 characters")
print("  • Wallet must contain only valid hex characters (0-9, a-f)")
print("  • Income must be a positive number")
print("  • Tax year must be between 2020-2030")
print()
print("✅ Ready to use! No more hardcoded wallet addresses.")
print()
print("To run: python hyperliquid_fetcher.py")
